import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import _app from "./_app";
import Header from "../components/common/header";

export default function Home() {
  return (
    <div>
      <Head>
        <title>GAKUNIQ AH</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favgakuniq.ico" />
      </Head>
      <Header />
    </div>
  );
}
